FROM python:3.12-slim

# Set environment variables
ENV FLASK_APP=app
ENV FLASK_ENV=development

# Install system dependencies
RUN apt-get update && apt-get install -y \
    pkg-config \
    default-libmysqlclient-dev \
    build-essential

# Install pipenv
RUN pip install --no-cache-dir pipenv

# Set the working directory
WORKDIR /app

# Copy Pipfile and Pipfile.lock to leverage Docker cache
COPY Pipfile Pipfile.lock ./

# Install dependencies using pipenv
RUN pipenv install --system --deploy

# Copy the rest of the application code
COPY . .

# Expose the development port
EXPOSE 5000

# Run the application
CMD ["flask", "run", "--host=0.0.0.0"]