FROM python:3.12-slim

WORKDIR /app

RUN pip install pipenv

COPY Pipfile Pipfile.lock ./
RUN pipenv install --system --dev

COPY . .

ENV FLASK_APP=app
ENV FLASK_ENV=dev
ENV FLASK_DEBUG=1

CMD ["flask", "run", "--host=0.0.0.0"]