# service-repos/auth_api/helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
  labels:
    app: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-api
  ports:
    - port: 5001
      targetPort: 5001